;;; java-imports-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from java-imports.el

(autoload 'java-imports-scan-file "java-imports" "\
Scans a java-mode or kotlin-mode buffer, adding any import class -> package
mappings to the import cache. If called with a prefix arguments
overwrites any existing cache entries for the file." t)
(autoload 'java-imports-list-imports "java-imports" "\
Return a list of all fully-qualified packages in the current
Java-mode or Kotlin-mode buffer" t)
(autoload 'java-imports-add-import-with-package "java-imports" "\
Add an import for the class for the name and package. Uses no caching.

(fn CLASS-NAME PACKAGE)" t)
(autoload 'java-imports-add-import "java-imports" "\
Import the Java class for the symbol at point. Uses the symbol
at the point for the class name, ask for a confirmation of the
class name before adding it.

Checks the import cache to see if a package entry exists for the
given class. If found, adds an import statement for the class. If
not found, prompts for the package and saves it to the cache.

If called with a prefix argument, overwrites the package for an
already-existing class name.

(fn CLASS-NAME)" t)
(autoload 'java-imports-add-import-dwim "java-imports" "\
Add an import statement for the class at point. If no class is
found, prompt for the class name. If the class's package already
exists in the cache, add it and return, otherwise prompt for the
package and cache it for future statements." t)
(autoload 'java-imports-scan-local-jars "java-imports" "\
scan the local repository, find local jars and add them to the cache.
if a class is found in multiple packages, any such package may be registered
for that class in the cache.
This is currently a synchronous and potentially slow operation, but
hopefully faster than adding imports manually or using eclipse

(fn &optional LOCAL-REPO)" t)
(register-definition-prefixes "java-imports" '("java-imports-"))

;;; End of scraped data

(provide 'java-imports-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; java-imports-autoloads.el ends here
