;;; javadoc-lookup-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from javadoc-import.el

(autoload 'javadoc-sort-imports "javadoc-import" "\
Sort the imports in the import section in proper order." t)
(define-obsolete-function-alias 'sort-java-imports 'javadoc-sort-imports "1.1.0")
(autoload 'javadoc-add-import "javadoc-import" "\
Insert an import statement at import section at the top of the file." t)
(define-obsolete-function-alias 'add-java-import 'javadoc-add-import "1.1.0")
(register-definition-prefixes "javadoc-import" '("jdl/"))


;;; Generated autoloads from javadoc-lookup.el

(autoload 'javadoc-lookup "javadoc-lookup" "\
Lookup based on class name.

(fn NAME)" t)
(register-definition-prefixes "javadoc-lookup" '("javadoc-" "jdl/"))


;;; Generated autoloads from maven-fetch.el

(autoload 'javadoc-add-artifacts "maven-fetch" "\
Add Maven repository artifacts to the javadoc-lookup index.
An artifact is specified by a sequence of three strings:
 [groupId artifactId version].

(fn &rest ARTIFACTS)")
(register-definition-prefixes "maven-fetch" '("maven-" "unzip-program-name"))

;;; End of scraped data

(provide 'javadoc-lookup-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; javadoc-lookup-autoloads.el ends here
