;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	keyboard-escape-quit
	move-dup-move-lines-down
	move-dup-move-lines-up
	))

(setq mc/cmds-to-run-once
      '(
	))
