;;; csproj-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from csproj-mode.el

(autoload 'csproj-mode-dotnet-new "csproj-mode" "\
Invoke 'dotnet new' with the given TEMPLATE-NAME.

(fn TEMPLATE-NAME)" t)
(autoload 'csproj-mode "csproj-mode" "\
A major mode for editing csproj and other msbuild-style project files

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.[^.]*proj\\'" . csproj-mode))
(register-definition-prefixes "csproj-mode" '("csproj-mode--get-dotnet-new-templates"))

;;; End of scraped data

(provide 'csproj-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; csproj-mode-autoloads.el ends here
